//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercurius.Sparrow.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mercurius.Sparrow.Entities.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生异常.
        /// </summary>
        public static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法执行完成.
        /// </summary>
        public static string ExecuteAfter {
            get {
                return ResourceManager.GetString("ExecuteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法开始执行.
        /// </summary>
        public static string ExecuteBefore {
            get {
                return ResourceManager.GetString("ExecuteBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ____LogerLevel.
        /// </summary>
        public static string LogerLevelCacheKey {
            get {
                return ResourceManager.GetString("LogerLevelCacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段长度不能超过{1}个字符！.
        /// </summary>
        public static string MaxStringLength {
            get {
                return ResourceManager.GetString("MaxStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础模块.
        /// </summary>
        public static string Model_Basic {
            get {
                return ResourceManager.GetString("Model_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基于角色的访问控制模块.
        /// </summary>
        public static string Model_RBAC {
            get {
                return ResourceManager.GetString("Model_RBAC", resourceCulture);
            }
        }
    }
}
